server {
    listen 80;

    location / {
        root /usr/share/nginx/html;
        index index.html;
        # Redirige todas las rutas al index.html
        # Necesario para que React Router funcione al refrescar
        try_files $uri $uri/ /index.html;
    }
}
